app/config/urls.py
from django.urls import path,include
from app.config.views import *

app_name = 'app.config'
urlpatterns = [
    path('ciudad',Ciudad ,name="ciudad"),
    path('crear-ciudad',CreateCiudad,name="crear-ciudad"),
    path('editar-ciudad/<int:pk>/',UpdateCiudad.as_view(),name="editar-ciudad"),
    path('consultar-ciudad/<int:pk>/', GetCiudad,name="consultar-ciudad"),
    path('departamento',Departamento ,name="departamento"),
    path('crear-departamento',CreateDepartamento,name="crear-departamento"),
    path('editar-departamento/<int:pk>/',UpdateDepartamento.as_view(),name="editar-departamento"),
    path('consultar-departamento/<int:pk>/', GetDepartamento,name="consultar-departamento"),
    path('log',Log ,name="log"),
]

app/index/urls.py
from django.urls import path,include
from . import views 
from django.conf import settings 
from django.conf.urls.static import static

app_name = 'app.index'
urlpatterns = [
    path('',views.index ,name="index"),    

]

segel/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.index.urls', namespace='index')),
    path('divipol/', include('app.divipol.urls', namespace='divipol')),
    path('configuracion/', include('app.config.urls', namespace='config')),
] + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

app/config/models.py
from django.db import models

class DepartamentoModel(models.Model):
    id = models.AutoField(db_column='id', primary_key=True)
    nombre = models.CharField(max_length=150,db_column='nombre',blank=False, null=False)
    is_active=models.BooleanField(default=True,blank=True, null=True)
    fecha_ingreso = models.DateTimeField(db_column='fecha_ingreso', auto_now_add=True,blank=True, null=True)

    def __str__(self):
        return self.nombre

    def get_estado(self):
        if self.is_active:
            return "Activo"
        else:
            return "Inactivo"
    class Meta:
        managed = True
        db_table = 'departamento'
        verbose_name="Departamento"
        verbose_name_plural= 'Departamentos' 

class CiudadModel(models.Model):
    id = models.AutoField(db_column='id', primary_key=True)
    nombre = models.CharField(max_length=150,db_column='nombre',blank=False, null=False)
    departamento = models.ForeignKey(DepartamentoModel, models.DO_NOTHING, db_column='departamento')
    is_active=models.BooleanField(default=True)
    fecha_ingreso = models.DateTimeField(db_column='fecha_ingreso', auto_now_add=True,blank=True, null=True)

    def __str__(self):
        return self.departamento

    def __str__(self):
        return self.nombre
   
    def get_estado(self):
        if self.is_active:
            return "Activo"
        else:
            return "Inactivo"

    class Meta:
        managed = True
        db_table = 'ciudad'
        verbose_name="ciudad"
        verbose_name_plural= 'ciudades' 

class ConfiguracionModel(models.Model):
    id = models.AutoField(db_column='id', primary_key=True)
    nombre = models.CharField(max_length=255,db_column='nombre',blank=False, null=False)
    manejador = models.CharField(max_length=50,db_column='manejador',blank=False, null=False)
    valor = models.CharField(max_length=255,db_column='valor',blank=False, null=False)
    is_active=models.BooleanField(default=False)
    fecha_ingreso = models.DateTimeField(db_column='fecha_ingreso', auto_now_add=True,blank=True, null=True)
    class Meta:
        managed = True
        db_table = 'configuracion'
        verbose_name="configuracion"
        verbose_name_plural= 'configuraciones' 


class LogModel(models.Model):
    id = models.AutoField(db_column='id', primary_key=True)
    modulo = models.CharField(db_column='modulo', max_length=300)
    request = models.CharField(db_column='request', max_length=800, null= True,blank=True)
    excepcion = models.CharField(db_column='excepcion', max_length=600)
    fecha_ingreso = models.DateTimeField(db_column='fecha_ingreso', auto_now_add=True)

    class Meta:
        managed = True
        db_table = 'log'
        verbose_name="log"
        verbose_name_plural= 'logs' 

class GeneroModel(models.Model):
    id = models.AutoField(db_column='id', primary_key=True)
    nombre = models.CharField(max_length=15, blank=False, null=False)
    is_active=models.BooleanField(default=False)

    class Meta:
        managed = True
        db_table = 'genero'
        verbose_name="genero"
        verbose_name_plural= 'generos' 

class TipoDocumentoModel(models.Model):
    id = models.AutoField(db_column='id', primary_key=True)
    nombre = models.CharField(max_length=30, blank=False, null=False)
    is_active=models.BooleanField(default=False)
    class Meta:
        managed = True
        db_table = 'tipo_documento'
        verbose_name="Tipo de documentos"
        verbose_name_plural= 'Tipo documentos' 

app/config/forms.py
from django import forms    
from app.config.models import *

class CiudadForm(forms.ModelForm):
        class Meta:
                model = CiudadModel
                fields = [
                        'departamento',
                        'nombre',    
                        'is_active'     
                ]
                labels = {
                        'departamento':'* Departamento', 
                        'nombre':'* Nombre',       
                        'is_active':'Activo'    
                }
                widgets = {
                        'departamento': forms.Select(attrs={'class': 'form-control border border-2'}),     
                        'nombre':forms.TextInput(attrs={'class': 'form-control border border-2'}),
                        'is_active': forms.CheckboxInput(attrs={})
                }

class DepartamentoForm(forms.ModelForm):
        class Meta:
                model = DepartamentoModel
                fields = [
                        'nombre',    
                        'is_active'     
                ]
                labels = {
                        'nombre':'* Nombre',       
                        'is_active':'Activo'    
                }
                widgets = {   
                        'nombre':forms.TextInput(attrs={'class': 'form-control border border-2'}),
                        'is_active': forms.CheckboxInput(attrs={})
                }

app/config/views.py
from django.shortcuts import render ,redirect
from django.views.generic import *
from app.usuario.models import *
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import *
from app.config.forms import *
from app.config.response import *
from app.config.models import *
from django.contrib.auth.mixins import LoginRequiredMixin
from app.config.response import *
from django.urls import reverse_lazy
from sweetify.views import SweetifySuccessMixin
import logging

# Create your views here.
@login_required
def Ciudad(request): 
    try:
        logger = logging.getLogger()
        login_url = '/perfil/login/'
        redirect_field_name = 'redirect_to'
        ciudad = CiudadModel.objects.all()
        form_class = CiudadForm
        departamento = DepartamentoModel.objects.all()
    except Exception as ex:
        logger.exception('Excepcion controlada: ' + str(ex))
        logger.error('Excepcion controlada: ' + str(ex))
    return render(request,'config/ciudad.html',locals())

@login_required
@require_http_methods(["POST"])
def CreateCiudad(request): 
    logger = logging.getLogger()
    modulo = "Config/AddCiudad"
    try:
        if request.method == "POST":
            ciudad = CiudadModel.objects.latest('id')
            departamento = request.POST.get('id_departamento')
            nombre = request.POST.get('id_nombre')
            if CiudadModel.objects.filter(nombre = nombre):
                response = Error("El nombre de la ciudad se encuentra registrado")
                RegistrarLog(modulo , "El nombre de la ciudad se encuentra registrado",request.POST)
            else:
                Ciudad = CiudadModel()
                departamento = DepartamentoModel.objects.get(id = departamento)
                id_ciudad = ciudad.id + 1
                Ciudad.id = id_ciudad
                Ciudad.departamento = departamento
                Ciudad.nombre = nombre
                Ciudad.save()
                sw = True
                if sw :
                    response = Success("Nombre de la ciudad registrado exitosamente")
                else:
                    response = Error("No se pudo registrar la ciudad")
                    RegistrarLog(modulo , "No se pudo registrar la ciudad",request.POST)
            return JsonResponse(response,safe=False)
    except Exception as ex:
        response = Error500('Informacion no procesada: ' + str(ex));
        logger.exception('Excepcion controlada: ' + str(ex))
        logger.error('Excepcion controlada: ' + str(ex))
        return JsonResponse(response,safe=False)

@login_required
@require_http_methods(["GET"])
def GetCiudad(request,pk):
    model = CiudadModel
    logger = logging.getLogger()
    modulo = "Config/GetCiudad"
    form = CiudadForm
    try:
        if request.method == "GET":
            if pk != None or pk != "":
                ciudad = model.objects.filter(id=pk).exists()
                if ciudad:
                    ciudad = model.objects.get(id=pk)
                    ciudad = {
                        'id' : ciudad.id,
                        'departamento': ciudad.departamento,
                        'nombre' : ciudad.nombre,
                        'estado': ciudad.is_active,
                        'form': form
                    }          
                    response = GetResponse("Ciudad encontrada",ciudad)
                else:
                    response = Error("Ciudad no encontrada")
                    RegistrarLog(modulo , "Ciudad no encontrada",request.POST)
            else:
                response = Error500("Ha ocurrido un error de validacion")
                RegistrarLog(modulo , "Ha ocurrido un error de validacion",request.POST)
            return render(request, 'config/modal-ciudad.html', response)
    except Exception as ex:
        response = Error500('Informacion no procesada: ' + str(ex));
        logger.exception('Excepcion controlada: ' + str(ex))
        logger.error('Excepcion controlada: ' + str(ex))
        RegistrarLog(modulo , "Ha ocurrido un error de validacion",request.POST)
        return JsonResponse(response,safe=False)


@login_required
@require_http_methods(["GET"])
def GetCiudadByDepartamento(request,pk):
    model = CiudadModel
    logger = logging.getLogger()
    modulo = "Config/GetCiudadByDepartamento"
    try:
        if request.method == "GET":
            if pk != None or pk != "":
                ciudad = model.objects.filter(departamento=pk).exists()
                if ciudad:
                    ciudad = model.objects.get(departamento=pk)
                else:
                    RegistrarLog(modulo , "Ciudad no encontrada",request.POST)
            else:
                RegistrarLog(modulo , "Ha ocurrido un error de validacion",request.POST)
            return render(request, locals())
    except Exception as ex:
        logger.exception('Excepcion controlada: ' + str(ex))
        logger.error('Excepcion controlada: ' + str(ex))
        RegistrarLog(modulo , "Ha ocurrido un error de validacion",request.POST)

class UpdateCiudad(LoginRequiredMixin,SweetifySuccessMixin,UpdateView):
    login_url = '/perfil/login/'
    redirect_field_name = 'redirect_to'
    model = CiudadModel
    success_url = reverse_lazy('config:ciudad')
    form_class = CiudadForm
    success_message = 'Ciudad actualizada exitosamente'
    def get_context_data(self, **kwargs):    
        context = super(UpdateCiudad, self).get_context_data(**kwargs)
        pk = self.kwargs.get('pk',0)
        ciudad = self.model.objects.get(id=pk)       
        if 'form' not in context:
            context['form'] = self.form_class(self.request.GET) 
        return context
        
    def post(self, request, *args, **kwargs):
        modulo = "Config/UpdateCiudad/post"
        self.object = self.get_object
        id = kwargs['pk']
        ciudad = self.model.objects.get(id=id)
        form = self.form_class(self.request.POST,instance=ciudad)  
        success_message = 'Ciudad actualizada exitosamente'  
        try:
            if form.is_valid():
                sw = form.save(commit=False)
                sw.save()
                SuccessMessage(self.request,'La ciudad se ha actualizado exitosamente')        
            else:
                ErrorMessage(self.request,'ha ocurrido un error al actualizar la ciudad')
                RegistrarLog(modulo, 'Ha ocurrido un error'+ str(form.errors) ,self.request.POST) 
                return render(request, 'config/ciudad.html', {'form': form})
            return redirect('config:ciudad')
        except Exception as ex:
            RegistrarLog(modulo, 'Excepcion controlada: '+ str(ex) ,self.request.POST)
            ErrorMessage(self.request,ex)
            return redirect('config:ciudad')

@login_required
def Departamento(request): 
    try:
        logger = logging.getLogger()
        login_url = '/perfil/login/'
        redirect_field_name = 'redirect_to'
        form_class = DepartamentoForm
        departamento = DepartamentoModel.objects.all()
    except Exception as ex:
        logger.exception('Excepcion controlada: ' + str(ex))
        logger.error('Excepcion controlada: ' + str(ex))
    return render(request,'config/departamento.html',locals())

            

@login_required
@require_http_methods(["POST"])
def CreateDepartamento(request):
        logger = logging.getLogger()
        modulo = "Config/CreateDepartamento/post"
        try:
            if  request.method == "POST":
                departamento = DepartamentoModel() 
                sw = DepartamentoModel.objects.latest('id')
                departamento.id = sw.id + 1
                departamento.nombre = request.POST.get('nombre')
                departamento.save()
                SuccessMessage(request,'El departamento se ha registrado correctamente')                    
            else:
                ErrorMessage(request,'Ha ocurrido un error')
                RegistrarLog(modulo, 'No se pudo guardar el departamento',request.POST) 
            return redirect('config:departamento') 
        except Exception as ex:
            RegistrarLog(modulo, 'Excepcion controlada: '+ str(ex) ,request.POST)
            ErrorMessage(request,ex)
            return redirect('config:departamento')



class UpdateDepartamento(LoginRequiredMixin,SweetifySuccessMixin,UpdateView):
    login_url = '/perfil/login/'
    redirect_field_name = 'redirect_to'
    model = DepartamentoModel
    success_url = reverse_lazy('config:departamento')
    form_class = DepartamentoForm
    success_message = 'Departamento actualizado exitosamente'
    def get_context_data(self, **kwargs):    
        context = super(UpdateDepartamento, self).get_context_data(**kwargs)
        pk = self.kwargs.get('pk',0)
        departamento = self.model.objects.get(id=pk)       
        if 'form' not in context:
            context['form'] = self.form_class(self.request.GET) 
        return context
        
    def post(self, request, *args, **kwargs):
        modulo = "Config/UpdateDepartamento/post"
        self.object = self.get_object
        id = kwargs['pk']
        departamento = self.model.objects.get(id=id)
        form = self.form_class(self.request.POST,instance=departamento)  
        success_message = 'Departamento actualizado exitosamente'  
        try:
            if form.is_valid():
                sw = form.save(commit=False)
                sw.save()
                SuccessMessage(self.request,'El departamento se ha actualizado exitosamente')        
            else:
                ErrorMessage(self.request,'ha ocurrido un error al actualizar el departamento')
                RegistrarLog(modulo, 'Ha ocurrido un error'+ str(form.errors) ,self.request.POST) 
                return render(request, 'config/departamento.html', {'form': form})
            return redirect('config:departamento')
        except Exception as ex:

templates/config/ciudad.html
{% extends 'layout/index.html' %}
{% block title %} SEGEL - ciudades {% endblock %}
{% block content %}
<section>
<div class="loader"></div>
    <div class="container-fluid">
    <div class="row">
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
            <div class="breadcrumb-holder">
                <h1 class="main-title float-left">Ciudades</h1>
                <ol class="breadcrumb float-right">
                    <li class="breadcrumb-item"><a href="{% url 'index:index' %}">Home</a></li>
                    <li class="breadcrumb-item active">Configuración</li>
                    <li class="breadcrumb-item active">Ciudades</li>
                </ol>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xl-7 col-lg-7 col-md-7 col-sm-12">
                   {% load sweetify %} {% sweetify %}
            <div class="card">
                    <div class="card-header">
                    <h3>
                        <div class="dropdown">
                                <i class="fa fa-list"></i> Lista de ciudades registradas
                            <button class="btn btn-info dropdown-toggle" type="button" id="MenuHerramienta"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Exportar
                            </button> 
                            <div class="dropdown-menu" id="MenuHerramientaCiudad" aria-labelledby="MenuHerramientaCiudad">

                            </div>
                        </div>
                        </h3>
                        </div>
                        <div class="card-body">
                                <div class="table-responsive">
                       {% if ciudad %}
                          <!--Aqui va la tabla-->
                          <table id="tablaciudad" class="table table-striped ">
                         
                                <thead class="bg-primary-custom text-white">
                                    <tr>
                                    <th>Id</th>
                                    <th>Departamento</th>
                                    <th>Nombre</th>
                                    <th>Estado</th>
                                    <th></th>
                                    </tr>
                                </thead>                             
                                <tbody>
                                {% for ciudad in ciudad %}
                                    <tr>
                                        <td>{{ ciudad.id }}</td>
                                        <td>{{ ciudad.departamento }}</td>
                                        <td>{{ ciudad.nombre }}</td>
                                        <td>{{ ciudad.get_estado }}</td>
                                        <td style="width:100px;">
                                            <a href="#" data-target="#modal_ciudad"  data-toggle="modal"  data-url="{% url 'config:consultar-ciudad' ciudad.id %}" 
                                                data-id="{{ ciudad.id }} "   class="modal_ciudad btn btn-success btn-circle btn-sm" title="Editar" data-placement="top" >
                                                <i class="fa fa-pencil" aria-hidden="true"></i>
                                            </a>
                                        </td>                               
                                    </tr>
                                {% endfor %}
                                </tbody>                            
                            </table>                           
                            <!--FIN DE TABLA-->
                            {% else %}
                                <div class="alert alert-danger">
                                    <span>
                                        <b>No hay ciudades registradas</b>
                                    </span>
                                </div>
                            {% endif %}
                </div>
            </div>
  
        </div>
    </div>
     <!--FIN MODULO DE REGISTRO DE CIUDAD-->
 <!--MODULO DE REGISTRO DE CIUDAD-->
        <div class="col-xl-5 col-lg-5 col-md-5 col-sm-12">
            <div class="card">
                <div class="card-header">
                    <h3><i class="fas fa-city"></i> Registrar ciudad </h3>
                </div>
                {% if departamento %}
                <div class="card-body">
                    <form class="FrmAddCiudad form-horizontal" id="FrmAddCiudad" name="FrmAddCiudad" data-url="{% url 'config:crear-ciudad' %}" method="POST" action="#" role="form">
                       {% csrf_token %}
                         <div class="form-group">
                            {{ form_class.departamento.label}}
                             {{ form_class.departamento}}
                         </div>
                        <div class="form-group">
                            {{ form_class.nombre.label}}
                             {{ form_class.nombre}}
                         </div>
                        {% if form.errors %}
                            <div class="alert alert-danger">
                                {{ form.errors }}
                            </div>
                        {% endif %}   
                            <div class="category">* Campo Requerido</div>
                        <div class="card-footer border-white bg-white text-center">
                            <button type="submit"  class="btn bg-primary-custom text-white btn-fill btn-wd">Guardar</button>
                        </div>
                    </form>
                </div>
                {% else %}
                    <div class="alert alert-danger">
                        <span>
                            <b>No hay departamentos registrados</b>
                        </span>
                    </div>
                 {% endif %}
            </div>
        </div>
    </div>
</div>
 <!--FIN MODULO DE REGISTRO DE CIUDAD-->
 <!--VENTANA MODAL DE CIUDAD-->
{% block modal_ciudad %}
 <div id="modal_ciudad" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content">
            <div class="modal-header bg-primary-custom ">
              <h5 class="modal-title text-light"><i class="fas fa-city" aria-hidden="true"></i></a>  Datos ciudad</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
             
            </div>
          </div>
        </div>
      </div>
    {% endblock %}
       <!--FIN VENTANA MODAL DE CIUDAD-->
</section>
{% endblock %}

templates/config/departamento.html
{% extends 'layout/index.html' %}
{% block title %} SEGEL - departamentos {% endblock %}
{% block content %}
<section>
<div class="container-fluid">
<div class="row">
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
            <div class="breadcrumb-holder">
                <h1 class="main-title float-left">Departamentos</h1>
                <ol class="breadcrumb float-right">
                    <li class="breadcrumb-item"><a href="{% url 'index:index' %}">Home</a></li>
                    <li class="breadcrumb-item active">Configuración</li>
                    <li class="breadcrumb-item active">Departamentos</li>
                </ol>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xl-7 col-lg-7 col-md-7 col-sm-12">
            {% load sweetify %} {% sweetify %}
            <div class="card">
                    <div class="card-header">
                        <h3>
                            <div class="dropdown">
                                    <i class="fa fa-list"></i> Lista de departamentos registrados
                              <button class="btn btn-info dropdown-toggle" type="button" id="MenuHerramienta"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Exportar
                                </button> 
                                <div class="dropdown-menu" id="MenuHerramientaDepartamento" aria-labelledby="MenuHerramientaDepartamento">
                                </div>
                            </div>
                        </h3>
                    </div>
                  <hr/>
                <div class="card-body">
                    <div class="table-responsive">
                    {% if departamento %}
                        <table id="tabladepartamento" class="table table-striped">
                            <thead class="bg-primary-custom text-white">
                                <tr>
                                <th>Id</th>
                                <th>Nombre</th>
                                <th>Estado</th>
                                <th></th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for departamento in departamento %}
                                <tr>
                                    <td>{{ departamento.id }}</td>
                                    <td>{{ departamento.nombre }}</td>
                                    <td>{{ departamento.get_estado }}</td>
                                    <td style="width:100px;">
                                        <a href="#" data-target="#modal_departamento"  data-url="{% url 'config:consultar-departamento' departamento.id %}"   data-id="{{ ciudad.id }} " 
                                            data-toggle="modal" class="modal_departamento btn btn-success btn-circle btn-sm" title="Editar"
                                            data-placement="top"> <i class="fa fa-eye" aria-hidden="true"></i>
                                        </a>                  
                                    </td>                                  
                                </tr>
                                    {% endfor %}
                            </tbody>                            
                        </table>
                        <!--FIN DE TABLA-->
                        {% else %}
                            <div class="alert alert-danger">
                                <span>
                                    <b>No hay ciudades registradas</b>
                                </span>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xl-5 col-lg-5 col-md-5 col-sm-12">
            <div class="card">
                <div class="card-content">
                    <div class="card-header">
                        <h3><i class="fas fa-flag"></i> Registrar departamento </h3>
                     </div>
                    <div class="card-body">
                        <form id="FrmAddDepartamento" name="FrmAddDepartamento" method="POST" action="{% url 'config:crear-departamento' %}" role="form">
                            {% csrf_token %}
                        <div class="form-group">
                            {{ form_class.nombre.label}}
                             {{ form_class.nombre}}
                          </div>
                            {% if form.errors %}
                                <div class="alert alert-danger">
                                    {{ form.errors }}
                                </div>
                            {% endif %} 
                            <div class="category">* Campo Requerido</div>               
                            <div class="card-footer bg-white border-white text-center">
                                <button type="submit" class="btn bg-primary-custom text-white btn-fill btn-wd">Guardar</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--VENTANA MODAL DE DEPÁRTAMENTOS-->
    {% block modal_departamento %}
    <div id="modal_departamento" class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                <div class="modal-header bg-primary-custom">
                    <h5 class="modal-title text-light"><i class="fas fa-flag" aria-hidden="true"></i></a> Datos departamento</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                </div>
                </div>
            </div>
         </div>
    </div>
    {% endblock %}
</section>
{% endblock %}